version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_ROOT_PASSWORD: rootpassword
      DB_NAME: payment_gateway
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_PORT: 3306
      DB_HOST: db
      GIN_MODE: release
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 1s
      timeout: 3s
      retries: 40
      start_period: 10s

  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: payment_gateway
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
