name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-e2e:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
#       Esta sendo executado apenas no linux pois os ambientes de windows e macos nao suportaram o docker compose para
#       execução dos testes e2e.
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Display Go version
        run: go version

      - name: Download dependencies
        run: go mod tidy

      - name: Start services
        run: docker compose -f docker-compose.e2e.yaml up --build -d

      - name: Wait for API to be healthy
        shell: bash
        run: |
          echo "Waiting for API container to become healthy on ${{ runner.os }}..."
          # Um pequeno sleep inicial pode ajudar em runners mais lentos
          sleep 15
          for i in {1..30}; do
            CONTAINER_ID=$(docker ps -q --filter "name=-app-")
            if [ -z "$CONTAINER_ID" ]; then
              echo "API container not found!"
              docker compose logs app
              exit 1
            fi
          
            HEALTH_STATUS=$(docker inspect -f '{{.State.Health.Status}}' $CONTAINER_ID)
            echo "Attempt $i: API health status is '$HEALTH_STATUS'"
          
            if [ "$HEALTH_STATUS" = "healthy" ]; then
              echo "API is healthy! Proceeding with tests."
              exit 0
            fi
            sleep 5
          done
          
          echo "Error: API did not become healthy in time."
          docker compose logs app 
          exit 1

      - name: Run tests with coverage
        run: go test -tags=e2e -v  ./...

      - name: Stop services
        if: always()
        run: docker compose -f docker-compose.e2e.yaml down

  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # You can change this to match your Go version

      - name: Display Go version
        run: go version

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: |
          go test -v -coverprofile='coverage.out' ./...

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ runner.os }}Add commentMore actions
          path: coverage.out