name: Go Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # You can change this to match your Go version

      - name: Display Go version
        run: go version

      - name: Download dependencies
        run: go mod tidy
        
      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          go test -v -covermode=atomic -coverprofile=coverage/coverage.out ./...
      
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ runner.os }}
          path: coverage/coverage.out

